# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/erikb/dev/demo/fork-eater

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/erikb/dev/demo/fork-eater

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/erikb/dev/demo/fork-eater/CMakeFiles /home/erikb/dev/demo/fork-eater//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/erikb/dev/demo/fork-eater/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/erikb/dev/demo/fork-eater/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named fork-eater

# Build rule for target.
fork-eater: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fork-eater
.PHONY : fork-eater

# fast build rule for target.
fork-eater/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/build
.PHONY : fork-eater/fast

external/glad.o: external/glad.c.o
.PHONY : external/glad.o

# target to build an object file
external/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/external/glad.c.o
.PHONY : external/glad.c.o

external/glad.i: external/glad.c.i
.PHONY : external/glad.i

# target to preprocess a source file
external/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/external/glad.c.i
.PHONY : external/glad.c.i

external/glad.s: external/glad.c.s
.PHONY : external/glad.s

# target to generate assembly for a file
external/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/external/glad.c.s
.PHONY : external/glad.c.s

external/imgui/backends/imgui_impl_glfw.o: external/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : external/imgui/backends/imgui_impl_glfw.o

# target to build an object file
external/imgui/backends/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/external/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : external/imgui/backends/imgui_impl_glfw.cpp.o

external/imgui/backends/imgui_impl_glfw.i: external/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : external/imgui/backends/imgui_impl_glfw.i

# target to preprocess a source file
external/imgui/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/external/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : external/imgui/backends/imgui_impl_glfw.cpp.i

external/imgui/backends/imgui_impl_glfw.s: external/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : external/imgui/backends/imgui_impl_glfw.s

# target to generate assembly for a file
external/imgui/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/external/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : external/imgui/backends/imgui_impl_glfw.cpp.s

external/imgui/backends/imgui_impl_opengl3.o: external/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : external/imgui/backends/imgui_impl_opengl3.o

# target to build an object file
external/imgui/backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/external/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : external/imgui/backends/imgui_impl_opengl3.cpp.o

external/imgui/backends/imgui_impl_opengl3.i: external/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : external/imgui/backends/imgui_impl_opengl3.i

# target to preprocess a source file
external/imgui/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/external/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : external/imgui/backends/imgui_impl_opengl3.cpp.i

external/imgui/backends/imgui_impl_opengl3.s: external/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : external/imgui/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
external/imgui/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/external/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : external/imgui/backends/imgui_impl_opengl3.cpp.s

external/imgui/imgui.o: external/imgui/imgui.cpp.o
.PHONY : external/imgui/imgui.o

# target to build an object file
external/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/external/imgui/imgui.cpp.o
.PHONY : external/imgui/imgui.cpp.o

external/imgui/imgui.i: external/imgui/imgui.cpp.i
.PHONY : external/imgui/imgui.i

# target to preprocess a source file
external/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/external/imgui/imgui.cpp.i
.PHONY : external/imgui/imgui.cpp.i

external/imgui/imgui.s: external/imgui/imgui.cpp.s
.PHONY : external/imgui/imgui.s

# target to generate assembly for a file
external/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/external/imgui/imgui.cpp.s
.PHONY : external/imgui/imgui.cpp.s

external/imgui/imgui_demo.o: external/imgui/imgui_demo.cpp.o
.PHONY : external/imgui/imgui_demo.o

# target to build an object file
external/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/external/imgui/imgui_demo.cpp.o
.PHONY : external/imgui/imgui_demo.cpp.o

external/imgui/imgui_demo.i: external/imgui/imgui_demo.cpp.i
.PHONY : external/imgui/imgui_demo.i

# target to preprocess a source file
external/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/external/imgui/imgui_demo.cpp.i
.PHONY : external/imgui/imgui_demo.cpp.i

external/imgui/imgui_demo.s: external/imgui/imgui_demo.cpp.s
.PHONY : external/imgui/imgui_demo.s

# target to generate assembly for a file
external/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/external/imgui/imgui_demo.cpp.s
.PHONY : external/imgui/imgui_demo.cpp.s

external/imgui/imgui_draw.o: external/imgui/imgui_draw.cpp.o
.PHONY : external/imgui/imgui_draw.o

# target to build an object file
external/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/external/imgui/imgui_draw.cpp.o
.PHONY : external/imgui/imgui_draw.cpp.o

external/imgui/imgui_draw.i: external/imgui/imgui_draw.cpp.i
.PHONY : external/imgui/imgui_draw.i

# target to preprocess a source file
external/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/external/imgui/imgui_draw.cpp.i
.PHONY : external/imgui/imgui_draw.cpp.i

external/imgui/imgui_draw.s: external/imgui/imgui_draw.cpp.s
.PHONY : external/imgui/imgui_draw.s

# target to generate assembly for a file
external/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/external/imgui/imgui_draw.cpp.s
.PHONY : external/imgui/imgui_draw.cpp.s

external/imgui/imgui_tables.o: external/imgui/imgui_tables.cpp.o
.PHONY : external/imgui/imgui_tables.o

# target to build an object file
external/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/external/imgui/imgui_tables.cpp.o
.PHONY : external/imgui/imgui_tables.cpp.o

external/imgui/imgui_tables.i: external/imgui/imgui_tables.cpp.i
.PHONY : external/imgui/imgui_tables.i

# target to preprocess a source file
external/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/external/imgui/imgui_tables.cpp.i
.PHONY : external/imgui/imgui_tables.cpp.i

external/imgui/imgui_tables.s: external/imgui/imgui_tables.cpp.s
.PHONY : external/imgui/imgui_tables.s

# target to generate assembly for a file
external/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/external/imgui/imgui_tables.cpp.s
.PHONY : external/imgui/imgui_tables.cpp.s

external/imgui/imgui_widgets.o: external/imgui/imgui_widgets.cpp.o
.PHONY : external/imgui/imgui_widgets.o

# target to build an object file
external/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/external/imgui/imgui_widgets.cpp.o
.PHONY : external/imgui/imgui_widgets.cpp.o

external/imgui/imgui_widgets.i: external/imgui/imgui_widgets.cpp.i
.PHONY : external/imgui/imgui_widgets.i

# target to preprocess a source file
external/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/external/imgui/imgui_widgets.cpp.i
.PHONY : external/imgui/imgui_widgets.cpp.i

external/imgui/imgui_widgets.s: external/imgui/imgui_widgets.cpp.s
.PHONY : external/imgui/imgui_widgets.s

# target to generate assembly for a file
external/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/external/imgui/imgui_widgets.cpp.s
.PHONY : external/imgui/imgui_widgets.cpp.s

src/FileManager.o: src/FileManager.cpp.o
.PHONY : src/FileManager.o

# target to build an object file
src/FileManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/FileManager.cpp.o
.PHONY : src/FileManager.cpp.o

src/FileManager.i: src/FileManager.cpp.i
.PHONY : src/FileManager.i

# target to preprocess a source file
src/FileManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/FileManager.cpp.i
.PHONY : src/FileManager.cpp.i

src/FileManager.s: src/FileManager.cpp.s
.PHONY : src/FileManager.s

# target to generate assembly for a file
src/FileManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/FileManager.cpp.s
.PHONY : src/FileManager.cpp.s

src/FileWatcher.o: src/FileWatcher.cpp.o
.PHONY : src/FileWatcher.o

# target to build an object file
src/FileWatcher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/FileWatcher.cpp.o
.PHONY : src/FileWatcher.cpp.o

src/FileWatcher.i: src/FileWatcher.cpp.i
.PHONY : src/FileWatcher.i

# target to preprocess a source file
src/FileWatcher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/FileWatcher.cpp.i
.PHONY : src/FileWatcher.cpp.i

src/FileWatcher.s: src/FileWatcher.cpp.s
.PHONY : src/FileWatcher.s

# target to generate assembly for a file
src/FileWatcher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/FileWatcher.cpp.s
.PHONY : src/FileWatcher.cpp.s

src/Framebuffer.o: src/Framebuffer.cpp.o
.PHONY : src/Framebuffer.o

# target to build an object file
src/Framebuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/Framebuffer.cpp.o
.PHONY : src/Framebuffer.cpp.o

src/Framebuffer.i: src/Framebuffer.cpp.i
.PHONY : src/Framebuffer.i

# target to preprocess a source file
src/Framebuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/Framebuffer.cpp.i
.PHONY : src/Framebuffer.cpp.i

src/Framebuffer.s: src/Framebuffer.cpp.s
.PHONY : src/Framebuffer.s

# target to generate assembly for a file
src/Framebuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/Framebuffer.cpp.s
.PHONY : src/Framebuffer.cpp.s

src/LeftPanel.o: src/LeftPanel.cpp.o
.PHONY : src/LeftPanel.o

# target to build an object file
src/LeftPanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/LeftPanel.cpp.o
.PHONY : src/LeftPanel.cpp.o

src/LeftPanel.i: src/LeftPanel.cpp.i
.PHONY : src/LeftPanel.i

# target to preprocess a source file
src/LeftPanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/LeftPanel.cpp.i
.PHONY : src/LeftPanel.cpp.i

src/LeftPanel.s: src/LeftPanel.cpp.s
.PHONY : src/LeftPanel.s

# target to generate assembly for a file
src/LeftPanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/LeftPanel.cpp.s
.PHONY : src/LeftPanel.cpp.s

src/Logger.o: src/Logger.cpp.o
.PHONY : src/Logger.o

# target to build an object file
src/Logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/Logger.cpp.o
.PHONY : src/Logger.cpp.o

src/Logger.i: src/Logger.cpp.i
.PHONY : src/Logger.i

# target to preprocess a source file
src/Logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/Logger.cpp.i
.PHONY : src/Logger.cpp.i

src/Logger.s: src/Logger.cpp.s
.PHONY : src/Logger.s

# target to generate assembly for a file
src/Logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/Logger.cpp.s
.PHONY : src/Logger.cpp.s

src/MenuSystem.o: src/MenuSystem.cpp.o
.PHONY : src/MenuSystem.o

# target to build an object file
src/MenuSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/MenuSystem.cpp.o
.PHONY : src/MenuSystem.cpp.o

src/MenuSystem.i: src/MenuSystem.cpp.i
.PHONY : src/MenuSystem.i

# target to preprocess a source file
src/MenuSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/MenuSystem.cpp.i
.PHONY : src/MenuSystem.cpp.i

src/MenuSystem.s: src/MenuSystem.cpp.s
.PHONY : src/MenuSystem.s

# target to generate assembly for a file
src/MenuSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/MenuSystem.cpp.s
.PHONY : src/MenuSystem.cpp.s

src/ParameterPanel.o: src/ParameterPanel.cpp.o
.PHONY : src/ParameterPanel.o

# target to build an object file
src/ParameterPanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/ParameterPanel.cpp.o
.PHONY : src/ParameterPanel.cpp.o

src/ParameterPanel.i: src/ParameterPanel.cpp.i
.PHONY : src/ParameterPanel.i

# target to preprocess a source file
src/ParameterPanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/ParameterPanel.cpp.i
.PHONY : src/ParameterPanel.cpp.i

src/ParameterPanel.s: src/ParameterPanel.cpp.s
.PHONY : src/ParameterPanel.s

# target to generate assembly for a file
src/ParameterPanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/ParameterPanel.cpp.s
.PHONY : src/ParameterPanel.cpp.s

src/PreviewPanel.o: src/PreviewPanel.cpp.o
.PHONY : src/PreviewPanel.o

# target to build an object file
src/PreviewPanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/PreviewPanel.cpp.o
.PHONY : src/PreviewPanel.cpp.o

src/PreviewPanel.i: src/PreviewPanel.cpp.i
.PHONY : src/PreviewPanel.i

# target to preprocess a source file
src/PreviewPanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/PreviewPanel.cpp.i
.PHONY : src/PreviewPanel.cpp.i

src/PreviewPanel.s: src/PreviewPanel.cpp.s
.PHONY : src/PreviewPanel.s

# target to generate assembly for a file
src/PreviewPanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/PreviewPanel.cpp.s
.PHONY : src/PreviewPanel.cpp.s

src/Settings.o: src/Settings.cpp.o
.PHONY : src/Settings.o

# target to build an object file
src/Settings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/Settings.cpp.o
.PHONY : src/Settings.cpp.o

src/Settings.i: src/Settings.cpp.i
.PHONY : src/Settings.i

# target to preprocess a source file
src/Settings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/Settings.cpp.i
.PHONY : src/Settings.cpp.i

src/Settings.s: src/Settings.cpp.s
.PHONY : src/Settings.s

# target to generate assembly for a file
src/Settings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/Settings.cpp.s
.PHONY : src/Settings.cpp.s

src/ShaderEditor.o: src/ShaderEditor.cpp.o
.PHONY : src/ShaderEditor.o

# target to build an object file
src/ShaderEditor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/ShaderEditor.cpp.o
.PHONY : src/ShaderEditor.cpp.o

src/ShaderEditor.i: src/ShaderEditor.cpp.i
.PHONY : src/ShaderEditor.i

# target to preprocess a source file
src/ShaderEditor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/ShaderEditor.cpp.i
.PHONY : src/ShaderEditor.cpp.i

src/ShaderEditor.s: src/ShaderEditor.cpp.s
.PHONY : src/ShaderEditor.s

# target to generate assembly for a file
src/ShaderEditor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/ShaderEditor.cpp.s
.PHONY : src/ShaderEditor.cpp.s

src/ShaderManager.o: src/ShaderManager.cpp.o
.PHONY : src/ShaderManager.o

# target to build an object file
src/ShaderManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/ShaderManager.cpp.o
.PHONY : src/ShaderManager.cpp.o

src/ShaderManager.i: src/ShaderManager.cpp.i
.PHONY : src/ShaderManager.i

# target to preprocess a source file
src/ShaderManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/ShaderManager.cpp.i
.PHONY : src/ShaderManager.cpp.i

src/ShaderManager.s: src/ShaderManager.cpp.s
.PHONY : src/ShaderManager.s

# target to generate assembly for a file
src/ShaderManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/ShaderManager.cpp.s
.PHONY : src/ShaderManager.cpp.s

src/ShaderPreprocessor.o: src/ShaderPreprocessor.cpp.o
.PHONY : src/ShaderPreprocessor.o

# target to build an object file
src/ShaderPreprocessor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/ShaderPreprocessor.cpp.o
.PHONY : src/ShaderPreprocessor.cpp.o

src/ShaderPreprocessor.i: src/ShaderPreprocessor.cpp.i
.PHONY : src/ShaderPreprocessor.i

# target to preprocess a source file
src/ShaderPreprocessor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/ShaderPreprocessor.cpp.i
.PHONY : src/ShaderPreprocessor.cpp.i

src/ShaderPreprocessor.s: src/ShaderPreprocessor.cpp.s
.PHONY : src/ShaderPreprocessor.s

# target to generate assembly for a file
src/ShaderPreprocessor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/ShaderPreprocessor.cpp.s
.PHONY : src/ShaderPreprocessor.cpp.s

src/ShaderProject.o: src/ShaderProject.cpp.o
.PHONY : src/ShaderProject.o

# target to build an object file
src/ShaderProject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/ShaderProject.cpp.o
.PHONY : src/ShaderProject.cpp.o

src/ShaderProject.i: src/ShaderProject.cpp.i
.PHONY : src/ShaderProject.i

# target to preprocess a source file
src/ShaderProject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/ShaderProject.cpp.i
.PHONY : src/ShaderProject.cpp.i

src/ShaderProject.s: src/ShaderProject.cpp.s
.PHONY : src/ShaderProject.s

# target to generate assembly for a file
src/ShaderProject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/ShaderProject.cpp.s
.PHONY : src/ShaderProject.cpp.s

src/ShaderTemplates.o: src/ShaderTemplates.cpp.o
.PHONY : src/ShaderTemplates.o

# target to build an object file
src/ShaderTemplates.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/ShaderTemplates.cpp.o
.PHONY : src/ShaderTemplates.cpp.o

src/ShaderTemplates.i: src/ShaderTemplates.cpp.i
.PHONY : src/ShaderTemplates.i

# target to preprocess a source file
src/ShaderTemplates.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/ShaderTemplates.cpp.i
.PHONY : src/ShaderTemplates.cpp.i

src/ShaderTemplates.s: src/ShaderTemplates.cpp.s
.PHONY : src/ShaderTemplates.s

# target to generate assembly for a file
src/ShaderTemplates.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/ShaderTemplates.cpp.s
.PHONY : src/ShaderTemplates.cpp.s

src/ShortcutManager.o: src/ShortcutManager.cpp.o
.PHONY : src/ShortcutManager.o

# target to build an object file
src/ShortcutManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/ShortcutManager.cpp.o
.PHONY : src/ShortcutManager.cpp.o

src/ShortcutManager.i: src/ShortcutManager.cpp.i
.PHONY : src/ShortcutManager.i

# target to preprocess a source file
src/ShortcutManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/ShortcutManager.cpp.i
.PHONY : src/ShortcutManager.cpp.i

src/ShortcutManager.s: src/ShortcutManager.cpp.s
.PHONY : src/ShortcutManager.s

# target to generate assembly for a file
src/ShortcutManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/ShortcutManager.cpp.s
.PHONY : src/ShortcutManager.cpp.s

src/Timeline.o: src/Timeline.cpp.o
.PHONY : src/Timeline.o

# target to build an object file
src/Timeline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/Timeline.cpp.o
.PHONY : src/Timeline.cpp.o

src/Timeline.i: src/Timeline.cpp.i
.PHONY : src/Timeline.i

# target to preprocess a source file
src/Timeline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/Timeline.cpp.i
.PHONY : src/Timeline.cpp.i

src/Timeline.s: src/Timeline.cpp.s
.PHONY : src/Timeline.s

# target to generate assembly for a file
src/Timeline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/Timeline.cpp.s
.PHONY : src/Timeline.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fork-eater.dir/build.make CMakeFiles/fork-eater.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... fork-eater"
	@echo "... glad"
	@echo "... external/glad.o"
	@echo "... external/glad.i"
	@echo "... external/glad.s"
	@echo "... external/imgui/backends/imgui_impl_glfw.o"
	@echo "... external/imgui/backends/imgui_impl_glfw.i"
	@echo "... external/imgui/backends/imgui_impl_glfw.s"
	@echo "... external/imgui/backends/imgui_impl_opengl3.o"
	@echo "... external/imgui/backends/imgui_impl_opengl3.i"
	@echo "... external/imgui/backends/imgui_impl_opengl3.s"
	@echo "... external/imgui/imgui.o"
	@echo "... external/imgui/imgui.i"
	@echo "... external/imgui/imgui.s"
	@echo "... external/imgui/imgui_demo.o"
	@echo "... external/imgui/imgui_demo.i"
	@echo "... external/imgui/imgui_demo.s"
	@echo "... external/imgui/imgui_draw.o"
	@echo "... external/imgui/imgui_draw.i"
	@echo "... external/imgui/imgui_draw.s"
	@echo "... external/imgui/imgui_tables.o"
	@echo "... external/imgui/imgui_tables.i"
	@echo "... external/imgui/imgui_tables.s"
	@echo "... external/imgui/imgui_widgets.o"
	@echo "... external/imgui/imgui_widgets.i"
	@echo "... external/imgui/imgui_widgets.s"
	@echo "... src/FileManager.o"
	@echo "... src/FileManager.i"
	@echo "... src/FileManager.s"
	@echo "... src/FileWatcher.o"
	@echo "... src/FileWatcher.i"
	@echo "... src/FileWatcher.s"
	@echo "... src/Framebuffer.o"
	@echo "... src/Framebuffer.i"
	@echo "... src/Framebuffer.s"
	@echo "... src/LeftPanel.o"
	@echo "... src/LeftPanel.i"
	@echo "... src/LeftPanel.s"
	@echo "... src/Logger.o"
	@echo "... src/Logger.i"
	@echo "... src/Logger.s"
	@echo "... src/MenuSystem.o"
	@echo "... src/MenuSystem.i"
	@echo "... src/MenuSystem.s"
	@echo "... src/ParameterPanel.o"
	@echo "... src/ParameterPanel.i"
	@echo "... src/ParameterPanel.s"
	@echo "... src/PreviewPanel.o"
	@echo "... src/PreviewPanel.i"
	@echo "... src/PreviewPanel.s"
	@echo "... src/Settings.o"
	@echo "... src/Settings.i"
	@echo "... src/Settings.s"
	@echo "... src/ShaderEditor.o"
	@echo "... src/ShaderEditor.i"
	@echo "... src/ShaderEditor.s"
	@echo "... src/ShaderManager.o"
	@echo "... src/ShaderManager.i"
	@echo "... src/ShaderManager.s"
	@echo "... src/ShaderPreprocessor.o"
	@echo "... src/ShaderPreprocessor.i"
	@echo "... src/ShaderPreprocessor.s"
	@echo "... src/ShaderProject.o"
	@echo "... src/ShaderProject.i"
	@echo "... src/ShaderProject.s"
	@echo "... src/ShaderTemplates.o"
	@echo "... src/ShaderTemplates.i"
	@echo "... src/ShaderTemplates.s"
	@echo "... src/ShortcutManager.o"
	@echo "... src/ShortcutManager.i"
	@echo "... src/ShortcutManager.s"
	@echo "... src/Timeline.o"
	@echo "... src/Timeline.i"
	@echo "... src/Timeline.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/erikb/dev/demo/fork-eater/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

